// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.1
// source: rpcapi/auth1.proto

package rpcapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// Auth1Client is the client API for Auth1 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type Auth1Client interface {
	GetSiteJwtSecret(ctx context.Context, in *SiteJwtSecretRequest, opts ...grpc.CallOption) (*SiteJwtSecretReply, error)
}

type auth1Client struct {
	cc grpc.ClientConnInterface
}

func NewAuth1Client(cc grpc.ClientConnInterface) Auth1Client {
	return &auth1Client{cc}
}

func (c *auth1Client) GetSiteJwtSecret(ctx context.Context, in *SiteJwtSecretRequest, opts ...grpc.CallOption) (*SiteJwtSecretReply, error) {
	out := new(SiteJwtSecretReply)
	err := c.cc.Invoke(ctx, "/rpcapi.Auth1/GetSiteJwtSecret", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Auth1Server is the server API for Auth1 service.
// All implementations must embed UnimplementedAuth1Server
// for forward compatibility
type Auth1Server interface {
	GetSiteJwtSecret(context.Context, *SiteJwtSecretRequest) (*SiteJwtSecretReply, error)
	mustEmbedUnimplementedAuth1Server()
}

// UnimplementedAuth1Server must be embedded to have forward compatible implementations.
type UnimplementedAuth1Server struct {
}

func (UnimplementedAuth1Server) GetSiteJwtSecret(context.Context, *SiteJwtSecretRequest) (*SiteJwtSecretReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSiteJwtSecret not implemented")
}
func (UnimplementedAuth1Server) mustEmbedUnimplementedAuth1Server() {}

// UnsafeAuth1Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to Auth1Server will
// result in compilation errors.
type UnsafeAuth1Server interface {
	mustEmbedUnimplementedAuth1Server()
}

func RegisterAuth1Server(s grpc.ServiceRegistrar, srv Auth1Server) {
	s.RegisterService(&Auth1_ServiceDesc, srv)
}

func _Auth1_GetSiteJwtSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SiteJwtSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Auth1Server).GetSiteJwtSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpcapi.Auth1/GetSiteJwtSecret",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Auth1Server).GetSiteJwtSecret(ctx, req.(*SiteJwtSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Auth1_ServiceDesc is the grpc.ServiceDesc for Auth1 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Auth1_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rpcapi.Auth1",
	HandlerType: (*Auth1Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSiteJwtSecret",
			Handler:    _Auth1_GetSiteJwtSecret_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpcapi/auth1.proto",
}
